/*
 * DocRaptor
 * A native client library for the DocRaptor HTML to PDF/XLS service.
 *
 * The version of the OpenAPI document: 2.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.docraptor;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import org.junit.Assert;
import org.junit.Ignore;
import org.junit.Test;


/**
 * Model tests for AsyncDoc
 */
public class AsyncDocTest {
    private final AsyncDoc model = new AsyncDoc();

    /**
     * Model tests for AsyncDoc
     */
    @Test
    public void testAsyncDoc() {
        // TODO: test AsyncDoc
    }

    /**
     * Test the property 'statusId'
     */
    @Test
    public void statusIdTest() {
        // TODO: test statusId
    }

}
