/*
 * DocRaptor
 * A native client library for the DocRaptor HTML to PDF/XLS service.
 *
 * The version of the OpenAPI document: 2.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.docraptor;

import com.docraptor.PrinceOptions;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import org.junit.Assert;
import org.junit.Ignore;
import org.junit.Test;


/**
 * Model tests for Doc
 */
public class DocTest {
    private final Doc model = new Doc();

    /**
     * Model tests for Doc
     */
    @Test
    public void testDoc() {
        // TODO: test Doc
    }

    /**
     * Test the property 'name'
     */
    @Test
    public void nameTest() {
        // TODO: test name
    }

    /**
     * Test the property 'documentType'
     */
    @Test
    public void documentTypeTest() {
        // TODO: test documentType
    }

    /**
     * Test the property 'documentContent'
     */
    @Test
    public void documentContentTest() {
        // TODO: test documentContent
    }

    /**
     * Test the property 'documentUrl'
     */
    @Test
    public void documentUrlTest() {
        // TODO: test documentUrl
    }

    /**
     * Test the property 'test'
     */
    @Test
    public void testTest() {
        // TODO: test test
    }

    /**
     * Test the property 'pipeline'
     */
    @Test
    public void pipelineTest() {
        // TODO: test pipeline
    }

    /**
     * Test the property 'strict'
     */
    @Test
    public void strictTest() {
        // TODO: test strict
    }

    /**
     * Test the property 'ignoreResourceErrors'
     */
    @Test
    public void ignoreResourceErrorsTest() {
        // TODO: test ignoreResourceErrors
    }

    /**
     * Test the property 'ignoreConsoleMessages'
     */
    @Test
    public void ignoreConsoleMessagesTest() {
        // TODO: test ignoreConsoleMessages
    }

    /**
     * Test the property 'tag'
     */
    @Test
    public void tagTest() {
        // TODO: test tag
    }

    /**
     * Test the property 'help'
     */
    @Test
    public void helpTest() {
        // TODO: test help
    }

    /**
     * Test the property 'javascript'
     */
    @Test
    public void javascriptTest() {
        // TODO: test javascript
    }

    /**
     * Test the property 'referrer'
     */
    @Test
    public void referrerTest() {
        // TODO: test referrer
    }

    /**
     * Test the property 'callbackUrl'
     */
    @Test
    public void callbackUrlTest() {
        // TODO: test callbackUrl
    }

    /**
     * Test the property 'hostedDownloadLimit'
     */
    @Test
    public void hostedDownloadLimitTest() {
        // TODO: test hostedDownloadLimit
    }

    /**
     * Test the property 'hostedExpiresAt'
     */
    @Test
    public void hostedExpiresAtTest() {
        // TODO: test hostedExpiresAt
    }

    /**
     * Test the property 'princeOptions'
     */
    @Test
    public void princeOptionsTest() {
        // TODO: test princeOptions
    }

}
