/*
 * DocRaptor
 * A native client library for the DocRaptor HTML to PDF/XLS service.
 *
 * The version of the OpenAPI document: 2.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.docraptor;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;

/**
 * AsyncDoc
 */
@JsonPropertyOrder({
  AsyncDoc.JSON_PROPERTY_STATUS_ID
})
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen")
public class AsyncDoc {
  public static final String JSON_PROPERTY_STATUS_ID = "status_id";
  private String statusId;

  public AsyncDoc() {
  }

  public AsyncDoc statusId(String statusId) {

    this.statusId = statusId;
    return this;
  }

   /**
   * The identifier used to get the status of the document using the status API.
   * @return statusId
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "The identifier used to get the status of the document using the status API.")
  @JsonProperty(JSON_PROPERTY_STATUS_ID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getStatusId() {
    return statusId;
  }


  @JsonProperty(JSON_PROPERTY_STATUS_ID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setStatusId(String statusId) {
    this.statusId = statusId;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    AsyncDoc asyncDoc = (AsyncDoc) o;
    return Objects.equals(this.statusId, asyncDoc.statusId);
  }

  @Override
  public int hashCode() {
    return Objects.hash(statusId);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class AsyncDoc {\n");
    sb.append("    statusId: ").append(toIndentedString(statusId)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

