/*
 * DocRaptor v1
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.2.0
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.docraptor;

import java.util.Objects;
import java.util.Arrays;
import com.docraptor.PrinceOptions;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;

/**
 * Doc
 */

public class Doc {
  @JsonProperty("pipeline")
  private String pipeline = null;

  @JsonProperty("name")
  private String name = null;

  /**
   * The type of document being created.
   */
  public enum DocumentTypeEnum {
    PDF("pdf"),

    XLS("xls"),

    XLSX("xlsx");

    private String value;

    DocumentTypeEnum(String value) {
      this.value = value;
    }

    @JsonValue
    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }

    @JsonCreator
    public static DocumentTypeEnum fromValue(String text) {
      for (DocumentTypeEnum b : DocumentTypeEnum.values()) {
        if (String.valueOf(b.value).equals(text)) {
          return b;
        }
      }
      return null;
    }
  }

  @JsonProperty("document_type")
  private DocumentTypeEnum documentType = null;

  @JsonProperty("document_content")
  private String documentContent = null;

  @JsonProperty("document_url")
  private String documentUrl = null;

  @JsonProperty("test")
  private Boolean test = true;

  /**
   * Force strict HTML validation.
   */
  public enum StrictEnum {
    NONE("none");

    private String value;

    StrictEnum(String value) {
      this.value = value;
    }

    @JsonValue
    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }

    @JsonCreator
    public static StrictEnum fromValue(String text) {
      for (StrictEnum b : StrictEnum.values()) {
        if (String.valueOf(b.value).equals(text)) {
          return b;
        }
      }
      return null;
    }
  }

  @JsonProperty("strict")
  private StrictEnum strict = StrictEnum.NONE;

  @JsonProperty("ignore_resource_errors")
  private Boolean ignoreResourceErrors = true;

  @JsonProperty("tag")
  private String tag = null;

  @JsonProperty("help")
  private Boolean help = false;

  @JsonProperty("javascript")
  private Boolean javascript = false;

  @JsonProperty("referrer")
  private String referrer = null;

  @JsonProperty("callback_url")
  private String callbackUrl = null;

  @JsonProperty("prince_options")
  private PrinceOptions princeOptions = null;

  public Doc pipeline(String pipeline) {
    this.pipeline = pipeline;
    return this;
  }

   /**
   * Specify a specific verison of the DocRaptor Pipeline to use.
   * @return pipeline
  **/
  @ApiModelProperty(value = "Specify a specific verison of the DocRaptor Pipeline to use.")
  public String getPipeline() {
    return pipeline;
  }

  public void setPipeline(String pipeline) {
    this.pipeline = pipeline;
  }

  public Doc name(String name) {
    this.name = name;
    return this;
  }

   /**
   * A name for identifying your document.
   * @return name
  **/
  @ApiModelProperty(required = true, value = "A name for identifying your document.")
  public String getName() {
    return name;
  }

  public void setName(String name) {
    this.name = name;
  }

  public Doc documentType(DocumentTypeEnum documentType) {
    this.documentType = documentType;
    return this;
  }

   /**
   * The type of document being created.
   * @return documentType
  **/
  @ApiModelProperty(required = true, value = "The type of document being created.")
  public DocumentTypeEnum getDocumentType() {
    return documentType;
  }

  public void setDocumentType(DocumentTypeEnum documentType) {
    this.documentType = documentType;
  }

  public Doc documentContent(String documentContent) {
    this.documentContent = documentContent;
    return this;
  }

   /**
   * The HTML data to be transformed into a document. You must supply content using document_content or document_url.
   * @return documentContent
  **/
  @ApiModelProperty(required = true, value = "The HTML data to be transformed into a document. You must supply content using document_content or document_url. ")
  public String getDocumentContent() {
    return documentContent;
  }

  public void setDocumentContent(String documentContent) {
    this.documentContent = documentContent;
  }

  public Doc documentUrl(String documentUrl) {
    this.documentUrl = documentUrl;
    return this;
  }

   /**
   * The URL to fetch the HTML data to be transformed into a document. You must supply content using document_content or document_url.
   * @return documentUrl
  **/
  @ApiModelProperty(value = "The URL to fetch the HTML data to be transformed into a document. You must supply content using document_content or document_url. ")
  public String getDocumentUrl() {
    return documentUrl;
  }

  public void setDocumentUrl(String documentUrl) {
    this.documentUrl = documentUrl;
  }

  public Doc test(Boolean test) {
    this.test = test;
    return this;
  }

   /**
   * Enable test mode for this document. Test documents are not charged for but include a watermark.
   * @return test
  **/
  @ApiModelProperty(value = "Enable test mode for this document. Test documents are not charged for but include a watermark.")
  public Boolean isTest() {
    return test;
  }

  public void setTest(Boolean test) {
    this.test = test;
  }

  public Doc strict(StrictEnum strict) {
    this.strict = strict;
    return this;
  }

   /**
   * Force strict HTML validation.
   * @return strict
  **/
  @ApiModelProperty(value = "Force strict HTML validation.")
  public StrictEnum getStrict() {
    return strict;
  }

  public void setStrict(StrictEnum strict) {
    this.strict = strict;
  }

  public Doc ignoreResourceErrors(Boolean ignoreResourceErrors) {
    this.ignoreResourceErrors = ignoreResourceErrors;
    return this;
  }

   /**
   * Failed loading of images/javascripts/stylesheets/etc. will not cause the rendering to stop.
   * @return ignoreResourceErrors
  **/
  @ApiModelProperty(value = "Failed loading of images/javascripts/stylesheets/etc. will not cause the rendering to stop.")
  public Boolean isIgnoreResourceErrors() {
    return ignoreResourceErrors;
  }

  public void setIgnoreResourceErrors(Boolean ignoreResourceErrors) {
    this.ignoreResourceErrors = ignoreResourceErrors;
  }

  public Doc tag(String tag) {
    this.tag = tag;
    return this;
  }

   /**
   * A field for storing a small amount of metadata with this document.
   * @return tag
  **/
  @ApiModelProperty(value = "A field for storing a small amount of metadata with this document.")
  public String getTag() {
    return tag;
  }

  public void setTag(String tag) {
    this.tag = tag;
  }

  public Doc help(Boolean help) {
    this.help = help;
    return this;
  }

   /**
   * Request support help with this request if it succeeds.
   * @return help
  **/
  @ApiModelProperty(value = "Request support help with this request if it succeeds.")
  public Boolean isHelp() {
    return help;
  }

  public void setHelp(Boolean help) {
    this.help = help;
  }

  public Doc javascript(Boolean javascript) {
    this.javascript = javascript;
    return this;
  }

   /**
   * Enable DocRaptor JavaScript parsing. PrinceXML JavaScript parsing is also available elsewhere.
   * @return javascript
  **/
  @ApiModelProperty(value = "Enable DocRaptor JavaScript parsing. PrinceXML JavaScript parsing is also available elsewhere.")
  public Boolean isJavascript() {
    return javascript;
  }

  public void setJavascript(Boolean javascript) {
    this.javascript = javascript;
  }

  public Doc referrer(String referrer) {
    this.referrer = referrer;
    return this;
  }

   /**
   * Set HTTP referrer when generating this document.
   * @return referrer
  **/
  @ApiModelProperty(value = "Set HTTP referrer when generating this document.")
  public String getReferrer() {
    return referrer;
  }

  public void setReferrer(String referrer) {
    this.referrer = referrer;
  }

  public Doc callbackUrl(String callbackUrl) {
    this.callbackUrl = callbackUrl;
    return this;
  }

   /**
   * A URL that will receive a POST request after successfully completing an asynchronous document. The POST data will include download_url and download_id similar to status api responses. WARNING: this only works on asynchronous documents.
   * @return callbackUrl
  **/
  @ApiModelProperty(value = "A URL that will receive a POST request after successfully completing an asynchronous document. The POST data will include download_url and download_id similar to status api responses. WARNING: this only works on asynchronous documents. ")
  public String getCallbackUrl() {
    return callbackUrl;
  }

  public void setCallbackUrl(String callbackUrl) {
    this.callbackUrl = callbackUrl;
  }

  public Doc princeOptions(PrinceOptions princeOptions) {
    this.princeOptions = princeOptions;
    return this;
  }

   /**
   * Get princeOptions
   * @return princeOptions
  **/
  @ApiModelProperty(value = "")
  public PrinceOptions getPrinceOptions() {
    return princeOptions;
  }

  public void setPrinceOptions(PrinceOptions princeOptions) {
    this.princeOptions = princeOptions;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    Doc doc = (Doc) o;
    return Objects.equals(this.pipeline, doc.pipeline) &&
        Objects.equals(this.name, doc.name) &&
        Objects.equals(this.documentType, doc.documentType) &&
        Objects.equals(this.documentContent, doc.documentContent) &&
        Objects.equals(this.documentUrl, doc.documentUrl) &&
        Objects.equals(this.test, doc.test) &&
        Objects.equals(this.strict, doc.strict) &&
        Objects.equals(this.ignoreResourceErrors, doc.ignoreResourceErrors) &&
        Objects.equals(this.tag, doc.tag) &&
        Objects.equals(this.help, doc.help) &&
        Objects.equals(this.javascript, doc.javascript) &&
        Objects.equals(this.referrer, doc.referrer) &&
        Objects.equals(this.callbackUrl, doc.callbackUrl) &&
        Objects.equals(this.princeOptions, doc.princeOptions);
  }

  @Override
  public int hashCode() {
    return Objects.hash(pipeline, name, documentType, documentContent, documentUrl, test, strict, ignoreResourceErrors, tag, help, javascript, referrer, callbackUrl, princeOptions);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class Doc {\n");

    sb.append("    pipeline: ").append(toIndentedString(pipeline)).append("\n");
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    documentType: ").append(toIndentedString(documentType)).append("\n");
    sb.append("    documentContent: ").append(toIndentedString(documentContent)).append("\n");
    sb.append("    documentUrl: ").append(toIndentedString(documentUrl)).append("\n");
    sb.append("    test: ").append(toIndentedString(test)).append("\n");
    sb.append("    strict: ").append(toIndentedString(strict)).append("\n");
    sb.append("    ignoreResourceErrors: ").append(toIndentedString(ignoreResourceErrors)).append("\n");
    sb.append("    tag: ").append(toIndentedString(tag)).append("\n");
    sb.append("    help: ").append(toIndentedString(help)).append("\n");
    sb.append("    javascript: ").append(toIndentedString(javascript)).append("\n");
    sb.append("    referrer: ").append(toIndentedString(referrer)).append("\n");
    sb.append("    callbackUrl: ").append(toIndentedString(callbackUrl)).append("\n");
    sb.append("    princeOptions: ").append(toIndentedString(princeOptions)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

