/*
 * DocRaptor
 * A native client library for the DocRaptor HTML to PDF/XLS service.
 *
 * The version of the OpenAPI document: 2.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.docraptor;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;

/**
 * DocStatus
 */
@JsonPropertyOrder({
  DocStatus.JSON_PROPERTY_STATUS,
  DocStatus.JSON_PROPERTY_DOWNLOAD_URL,
  DocStatus.JSON_PROPERTY_DOWNLOAD_ID,
  DocStatus.JSON_PROPERTY_MESSAGE,
  DocStatus.JSON_PROPERTY_NUMBER_OF_PAGES,
  DocStatus.JSON_PROPERTY_VALIDATION_ERRORS
})
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen")
public class DocStatus {
  public static final String JSON_PROPERTY_STATUS = "status";
  private String status;

  public static final String JSON_PROPERTY_DOWNLOAD_URL = "download_url";
  private String downloadUrl;

  public static final String JSON_PROPERTY_DOWNLOAD_ID = "download_id";
  private String downloadId;

  public static final String JSON_PROPERTY_MESSAGE = "message";
  private String message;

  public static final String JSON_PROPERTY_NUMBER_OF_PAGES = "number_of_pages";
  private Integer numberOfPages;

  public static final String JSON_PROPERTY_VALIDATION_ERRORS = "validation_errors";
  private String validationErrors;

  public DocStatus() {
  }

  public DocStatus status(String status) {

    this.status = status;
    return this;
  }

   /**
   * The present status of the document. Can be queued, working, completed, and failed.
   * @return status
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "The present status of the document. Can be queued, working, completed, and failed.")
  @JsonProperty(JSON_PROPERTY_STATUS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getStatus() {
    return status;
  }


  @JsonProperty(JSON_PROPERTY_STATUS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setStatus(String status) {
    this.status = status;
  }


  public DocStatus downloadUrl(String downloadUrl) {

    this.downloadUrl = downloadUrl;
    return this;
  }

   /**
   * The URL where the document can be retrieved. This URL may only be used a few times.
   * @return downloadUrl
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "The URL where the document can be retrieved. This URL may only be used a few times.")
  @JsonProperty(JSON_PROPERTY_DOWNLOAD_URL)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getDownloadUrl() {
    return downloadUrl;
  }


  @JsonProperty(JSON_PROPERTY_DOWNLOAD_URL)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setDownloadUrl(String downloadUrl) {
    this.downloadUrl = downloadUrl;
  }


  public DocStatus downloadId(String downloadId) {

    this.downloadId = downloadId;
    return this;
  }

   /**
   * The identifier for downloading the document with the download API.
   * @return downloadId
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "The identifier for downloading the document with the download API.")
  @JsonProperty(JSON_PROPERTY_DOWNLOAD_ID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getDownloadId() {
    return downloadId;
  }


  @JsonProperty(JSON_PROPERTY_DOWNLOAD_ID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setDownloadId(String downloadId) {
    this.downloadId = downloadId;
  }


  public DocStatus message(String message) {

    this.message = message;
    return this;
  }

   /**
   * Additional information.
   * @return message
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "Additional information.")
  @JsonProperty(JSON_PROPERTY_MESSAGE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getMessage() {
    return message;
  }


  @JsonProperty(JSON_PROPERTY_MESSAGE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setMessage(String message) {
    this.message = message;
  }


  public DocStatus numberOfPages(Integer numberOfPages) {

    this.numberOfPages = numberOfPages;
    return this;
  }

   /**
   * Number of PDF pages in document.
   * @return numberOfPages
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "Number of PDF pages in document.")
  @JsonProperty(JSON_PROPERTY_NUMBER_OF_PAGES)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Integer getNumberOfPages() {
    return numberOfPages;
  }


  @JsonProperty(JSON_PROPERTY_NUMBER_OF_PAGES)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setNumberOfPages(Integer numberOfPages) {
    this.numberOfPages = numberOfPages;
  }


  public DocStatus validationErrors(String validationErrors) {

    this.validationErrors = validationErrors;
    return this;
  }

   /**
   * Error information.
   * @return validationErrors
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "Error information.")
  @JsonProperty(JSON_PROPERTY_VALIDATION_ERRORS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getValidationErrors() {
    return validationErrors;
  }


  @JsonProperty(JSON_PROPERTY_VALIDATION_ERRORS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setValidationErrors(String validationErrors) {
    this.validationErrors = validationErrors;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    DocStatus docStatus = (DocStatus) o;
    return Objects.equals(this.status, docStatus.status) &&
        Objects.equals(this.downloadUrl, docStatus.downloadUrl) &&
        Objects.equals(this.downloadId, docStatus.downloadId) &&
        Objects.equals(this.message, docStatus.message) &&
        Objects.equals(this.numberOfPages, docStatus.numberOfPages) &&
        Objects.equals(this.validationErrors, docStatus.validationErrors);
  }

  @Override
  public int hashCode() {
    return Objects.hash(status, downloadUrl, downloadId, message, numberOfPages, validationErrors);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class DocStatus {\n");
    sb.append("    status: ").append(toIndentedString(status)).append("\n");
    sb.append("    downloadUrl: ").append(toIndentedString(downloadUrl)).append("\n");
    sb.append("    downloadId: ").append(toIndentedString(downloadId)).append("\n");
    sb.append("    message: ").append(toIndentedString(message)).append("\n");
    sb.append("    numberOfPages: ").append(toIndentedString(numberOfPages)).append("\n");
    sb.append("    validationErrors: ").append(toIndentedString(validationErrors)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

