/*
 * DocRaptor
 * A native client library for the DocRaptor HTML to PDF/XLS service.
 *
 * The version of the OpenAPI document: 2.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.docraptor;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;

/**
 * PrinceOptions
 */
@JsonPropertyOrder({
  PrinceOptions.JSON_PROPERTY_BASEURL,
  PrinceOptions.JSON_PROPERTY_NO_XINCLUDE,
  PrinceOptions.JSON_PROPERTY_NO_NETWORK,
  PrinceOptions.JSON_PROPERTY_NO_PARALLEL_DOWNLOADS,
  PrinceOptions.JSON_PROPERTY_HTTP_USER,
  PrinceOptions.JSON_PROPERTY_HTTP_PASSWORD,
  PrinceOptions.JSON_PROPERTY_HTTP_PROXY,
  PrinceOptions.JSON_PROPERTY_HTTP_TIMEOUT,
  PrinceOptions.JSON_PROPERTY_INSECURE,
  PrinceOptions.JSON_PROPERTY_MEDIA,
  PrinceOptions.JSON_PROPERTY_NO_AUTHOR_STYLE,
  PrinceOptions.JSON_PROPERTY_NO_DEFAULT_STYLE,
  PrinceOptions.JSON_PROPERTY_NO_EMBED_FONTS,
  PrinceOptions.JSON_PROPERTY_NO_SUBSET_FONTS,
  PrinceOptions.JSON_PROPERTY_NO_COMPRESS,
  PrinceOptions.JSON_PROPERTY_ENCRYPT,
  PrinceOptions.JSON_PROPERTY_KEY_BITS,
  PrinceOptions.JSON_PROPERTY_USER_PASSWORD,
  PrinceOptions.JSON_PROPERTY_OWNER_PASSWORD,
  PrinceOptions.JSON_PROPERTY_DISALLOW_PRINT,
  PrinceOptions.JSON_PROPERTY_DISALLOW_COPY,
  PrinceOptions.JSON_PROPERTY_DISALLOW_ANNOTATE,
  PrinceOptions.JSON_PROPERTY_DISALLOW_MODIFY,
  PrinceOptions.JSON_PROPERTY_DEBUG,
  PrinceOptions.JSON_PROPERTY_INPUT,
  PrinceOptions.JSON_PROPERTY_VERSION,
  PrinceOptions.JSON_PROPERTY_JAVASCRIPT,
  PrinceOptions.JSON_PROPERTY_CSS_DPI,
  PrinceOptions.JSON_PROPERTY_PROFILE,
  PrinceOptions.JSON_PROPERTY_PDF_TITLE
})
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen")
public class PrinceOptions {
  public static final String JSON_PROPERTY_BASEURL = "baseurl";
  private String baseurl;

  public static final String JSON_PROPERTY_NO_XINCLUDE = "no_xinclude";
  private Boolean noXinclude;

  public static final String JSON_PROPERTY_NO_NETWORK = "no_network";
  private Boolean noNetwork;

  public static final String JSON_PROPERTY_NO_PARALLEL_DOWNLOADS = "no_parallel_downloads";
  private Boolean noParallelDownloads;

  public static final String JSON_PROPERTY_HTTP_USER = "http_user";
  private String httpUser;

  public static final String JSON_PROPERTY_HTTP_PASSWORD = "http_password";
  private String httpPassword;

  public static final String JSON_PROPERTY_HTTP_PROXY = "http_proxy";
  private String httpProxy;

  public static final String JSON_PROPERTY_HTTP_TIMEOUT = "http_timeout";
  private Integer httpTimeout;

  public static final String JSON_PROPERTY_INSECURE = "insecure";
  private Boolean insecure;

  public static final String JSON_PROPERTY_MEDIA = "media";
  private String media = "print";

  public static final String JSON_PROPERTY_NO_AUTHOR_STYLE = "no_author_style";
  private Boolean noAuthorStyle;

  public static final String JSON_PROPERTY_NO_DEFAULT_STYLE = "no_default_style";
  private Boolean noDefaultStyle;

  public static final String JSON_PROPERTY_NO_EMBED_FONTS = "no_embed_fonts";
  private Boolean noEmbedFonts;

  public static final String JSON_PROPERTY_NO_SUBSET_FONTS = "no_subset_fonts";
  private Boolean noSubsetFonts;

  public static final String JSON_PROPERTY_NO_COMPRESS = "no_compress";
  private Boolean noCompress;

  public static final String JSON_PROPERTY_ENCRYPT = "encrypt";
  private Boolean encrypt;

  public static final String JSON_PROPERTY_KEY_BITS = "key_bits";
  private Integer keyBits;

  public static final String JSON_PROPERTY_USER_PASSWORD = "user_password";
  private String userPassword;

  public static final String JSON_PROPERTY_OWNER_PASSWORD = "owner_password";
  private String ownerPassword;

  public static final String JSON_PROPERTY_DISALLOW_PRINT = "disallow_print";
  private Boolean disallowPrint;

  public static final String JSON_PROPERTY_DISALLOW_COPY = "disallow_copy";
  private Boolean disallowCopy;

  public static final String JSON_PROPERTY_DISALLOW_ANNOTATE = "disallow_annotate";
  private Boolean disallowAnnotate;

  public static final String JSON_PROPERTY_DISALLOW_MODIFY = "disallow_modify";
  private Boolean disallowModify;

  public static final String JSON_PROPERTY_DEBUG = "debug";
  private Boolean debug;

  /**
   * Specify the input format.
   */
  public enum InputEnum {
    HTML("html"),

    XML("xml"),

    AUTO("auto");

    private String value;

    InputEnum(String value) {
      this.value = value;
    }

    @JsonValue
    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }

    @JsonCreator
    public static InputEnum fromValue(String value) {
      for (InputEnum b : InputEnum.values()) {
        if (b.value.equals(value)) {
          return b;
        }
      }
      throw new IllegalArgumentException("Unexpected value '" + value + "'");
    }
  }

  public static final String JSON_PROPERTY_INPUT = "input";
  private InputEnum input = InputEnum.HTML;

  public static final String JSON_PROPERTY_VERSION = "version";
  private String version;

  public static final String JSON_PROPERTY_JAVASCRIPT = "javascript";
  private Boolean javascript;

  public static final String JSON_PROPERTY_CSS_DPI = "css_dpi";
  private Integer cssDpi;

  public static final String JSON_PROPERTY_PROFILE = "profile";
  private String profile;

  public static final String JSON_PROPERTY_PDF_TITLE = "pdf_title";
  private String pdfTitle;

  public PrinceOptions() {
  }

  public PrinceOptions baseurl(String baseurl) {

    this.baseurl = baseurl;
    return this;
  }

   /**
   * Set the baseurl for assets.
   * @return baseurl
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "Set the baseurl for assets.")
  @JsonProperty(JSON_PROPERTY_BASEURL)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getBaseurl() {
    return baseurl;
  }


  @JsonProperty(JSON_PROPERTY_BASEURL)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setBaseurl(String baseurl) {
    this.baseurl = baseurl;
  }


  public PrinceOptions noXinclude(Boolean noXinclude) {

    this.noXinclude = noXinclude;
    return this;
  }

   /**
   * Disable XML inclusion.
   * @return noXinclude
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "Disable XML inclusion.")
  @JsonProperty(JSON_PROPERTY_NO_XINCLUDE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Boolean getNoXinclude() {
    return noXinclude;
  }


  @JsonProperty(JSON_PROPERTY_NO_XINCLUDE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setNoXinclude(Boolean noXinclude) {
    this.noXinclude = noXinclude;
  }


  public PrinceOptions noNetwork(Boolean noNetwork) {

    this.noNetwork = noNetwork;
    return this;
  }

   /**
   * Disable network access.
   * @return noNetwork
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "Disable network access.")
  @JsonProperty(JSON_PROPERTY_NO_NETWORK)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Boolean getNoNetwork() {
    return noNetwork;
  }


  @JsonProperty(JSON_PROPERTY_NO_NETWORK)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setNoNetwork(Boolean noNetwork) {
    this.noNetwork = noNetwork;
  }


  public PrinceOptions noParallelDownloads(Boolean noParallelDownloads) {

    this.noParallelDownloads = noParallelDownloads;
    return this;
  }

   /**
   * Disables parallel fetching of assets during PDF creation. Useful if your asset host has strict rate limiting.
   * @return noParallelDownloads
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "Disables parallel fetching of assets during PDF creation. Useful if your asset host has strict rate limiting.")
  @JsonProperty(JSON_PROPERTY_NO_PARALLEL_DOWNLOADS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Boolean getNoParallelDownloads() {
    return noParallelDownloads;
  }


  @JsonProperty(JSON_PROPERTY_NO_PARALLEL_DOWNLOADS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setNoParallelDownloads(Boolean noParallelDownloads) {
    this.noParallelDownloads = noParallelDownloads;
  }


  public PrinceOptions httpUser(String httpUser) {

    this.httpUser = httpUser;
    return this;
  }

   /**
   * Set the user for HTTP authentication.
   * @return httpUser
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "Set the user for HTTP authentication.")
  @JsonProperty(JSON_PROPERTY_HTTP_USER)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getHttpUser() {
    return httpUser;
  }


  @JsonProperty(JSON_PROPERTY_HTTP_USER)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setHttpUser(String httpUser) {
    this.httpUser = httpUser;
  }


  public PrinceOptions httpPassword(String httpPassword) {

    this.httpPassword = httpPassword;
    return this;
  }

   /**
   * Set the password for HTTP authentication.
   * @return httpPassword
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "Set the password for HTTP authentication.")
  @JsonProperty(JSON_PROPERTY_HTTP_PASSWORD)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getHttpPassword() {
    return httpPassword;
  }


  @JsonProperty(JSON_PROPERTY_HTTP_PASSWORD)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setHttpPassword(String httpPassword) {
    this.httpPassword = httpPassword;
  }


  public PrinceOptions httpProxy(String httpProxy) {

    this.httpProxy = httpProxy;
    return this;
  }

   /**
   * Set the HTTP proxy server.
   * @return httpProxy
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "Set the HTTP proxy server.")
  @JsonProperty(JSON_PROPERTY_HTTP_PROXY)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getHttpProxy() {
    return httpProxy;
  }


  @JsonProperty(JSON_PROPERTY_HTTP_PROXY)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setHttpProxy(String httpProxy) {
    this.httpProxy = httpProxy;
  }


  public PrinceOptions httpTimeout(Integer httpTimeout) {

    this.httpTimeout = httpTimeout;
    return this;
  }

   /**
   * Set the HTTP request timeout.
   * @return httpTimeout
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "Set the HTTP request timeout.")
  @JsonProperty(JSON_PROPERTY_HTTP_TIMEOUT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Integer getHttpTimeout() {
    return httpTimeout;
  }


  @JsonProperty(JSON_PROPERTY_HTTP_TIMEOUT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setHttpTimeout(Integer httpTimeout) {
    this.httpTimeout = httpTimeout;
  }


  public PrinceOptions insecure(Boolean insecure) {

    this.insecure = insecure;
    return this;
  }

   /**
   * Disable SSL verification.
   * @return insecure
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "Disable SSL verification.")
  @JsonProperty(JSON_PROPERTY_INSECURE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Boolean getInsecure() {
    return insecure;
  }


  @JsonProperty(JSON_PROPERTY_INSECURE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setInsecure(Boolean insecure) {
    this.insecure = insecure;
  }


  public PrinceOptions media(String media) {

    this.media = media;
    return this;
  }

   /**
   * Specify the CSS media type. Defaults to \&quot;print\&quot; but you may want to use \&quot;screen\&quot; for web styles.
   * @return media
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "Specify the CSS media type. Defaults to \"print\" but you may want to use \"screen\" for web styles.")
  @JsonProperty(JSON_PROPERTY_MEDIA)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getMedia() {
    return media;
  }


  @JsonProperty(JSON_PROPERTY_MEDIA)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setMedia(String media) {
    this.media = media;
  }


  public PrinceOptions noAuthorStyle(Boolean noAuthorStyle) {

    this.noAuthorStyle = noAuthorStyle;
    return this;
  }

   /**
   * Ignore author stylesheets.
   * @return noAuthorStyle
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "Ignore author stylesheets.")
  @JsonProperty(JSON_PROPERTY_NO_AUTHOR_STYLE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Boolean getNoAuthorStyle() {
    return noAuthorStyle;
  }


  @JsonProperty(JSON_PROPERTY_NO_AUTHOR_STYLE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setNoAuthorStyle(Boolean noAuthorStyle) {
    this.noAuthorStyle = noAuthorStyle;
  }


  public PrinceOptions noDefaultStyle(Boolean noDefaultStyle) {

    this.noDefaultStyle = noDefaultStyle;
    return this;
  }

   /**
   * Ignore default stylesheets.
   * @return noDefaultStyle
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "Ignore default stylesheets.")
  @JsonProperty(JSON_PROPERTY_NO_DEFAULT_STYLE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Boolean getNoDefaultStyle() {
    return noDefaultStyle;
  }


  @JsonProperty(JSON_PROPERTY_NO_DEFAULT_STYLE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setNoDefaultStyle(Boolean noDefaultStyle) {
    this.noDefaultStyle = noDefaultStyle;
  }


  public PrinceOptions noEmbedFonts(Boolean noEmbedFonts) {

    this.noEmbedFonts = noEmbedFonts;
    return this;
  }

   /**
   * Disable font embedding in PDFs.
   * @return noEmbedFonts
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "Disable font embedding in PDFs.")
  @JsonProperty(JSON_PROPERTY_NO_EMBED_FONTS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Boolean getNoEmbedFonts() {
    return noEmbedFonts;
  }


  @JsonProperty(JSON_PROPERTY_NO_EMBED_FONTS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setNoEmbedFonts(Boolean noEmbedFonts) {
    this.noEmbedFonts = noEmbedFonts;
  }


  public PrinceOptions noSubsetFonts(Boolean noSubsetFonts) {

    this.noSubsetFonts = noSubsetFonts;
    return this;
  }

   /**
   * Disable font subsetting in PDFs.
   * @return noSubsetFonts
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "Disable font subsetting in PDFs.")
  @JsonProperty(JSON_PROPERTY_NO_SUBSET_FONTS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Boolean getNoSubsetFonts() {
    return noSubsetFonts;
  }


  @JsonProperty(JSON_PROPERTY_NO_SUBSET_FONTS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setNoSubsetFonts(Boolean noSubsetFonts) {
    this.noSubsetFonts = noSubsetFonts;
  }


  public PrinceOptions noCompress(Boolean noCompress) {

    this.noCompress = noCompress;
    return this;
  }

   /**
   * Disable PDF compression.
   * @return noCompress
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "Disable PDF compression.")
  @JsonProperty(JSON_PROPERTY_NO_COMPRESS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Boolean getNoCompress() {
    return noCompress;
  }


  @JsonProperty(JSON_PROPERTY_NO_COMPRESS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setNoCompress(Boolean noCompress) {
    this.noCompress = noCompress;
  }


  public PrinceOptions encrypt(Boolean encrypt) {

    this.encrypt = encrypt;
    return this;
  }

   /**
   * Encrypt PDF output.
   * @return encrypt
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "Encrypt PDF output.")
  @JsonProperty(JSON_PROPERTY_ENCRYPT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Boolean getEncrypt() {
    return encrypt;
  }


  @JsonProperty(JSON_PROPERTY_ENCRYPT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setEncrypt(Boolean encrypt) {
    this.encrypt = encrypt;
  }


  public PrinceOptions keyBits(Integer keyBits) {

    this.keyBits = keyBits;
    return this;
  }

   /**
   * Set encryption key size.
   * @return keyBits
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "Set encryption key size.")
  @JsonProperty(JSON_PROPERTY_KEY_BITS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Integer getKeyBits() {
    return keyBits;
  }


  @JsonProperty(JSON_PROPERTY_KEY_BITS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setKeyBits(Integer keyBits) {
    this.keyBits = keyBits;
  }


  public PrinceOptions userPassword(String userPassword) {

    this.userPassword = userPassword;
    return this;
  }

   /**
   * Set the PDF user password.
   * @return userPassword
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "Set the PDF user password.")
  @JsonProperty(JSON_PROPERTY_USER_PASSWORD)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getUserPassword() {
    return userPassword;
  }


  @JsonProperty(JSON_PROPERTY_USER_PASSWORD)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setUserPassword(String userPassword) {
    this.userPassword = userPassword;
  }


  public PrinceOptions ownerPassword(String ownerPassword) {

    this.ownerPassword = ownerPassword;
    return this;
  }

   /**
   * Set the PDF owner password.
   * @return ownerPassword
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "Set the PDF owner password.")
  @JsonProperty(JSON_PROPERTY_OWNER_PASSWORD)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getOwnerPassword() {
    return ownerPassword;
  }


  @JsonProperty(JSON_PROPERTY_OWNER_PASSWORD)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setOwnerPassword(String ownerPassword) {
    this.ownerPassword = ownerPassword;
  }


  public PrinceOptions disallowPrint(Boolean disallowPrint) {

    this.disallowPrint = disallowPrint;
    return this;
  }

   /**
   * Disallow printing of this PDF.
   * @return disallowPrint
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "Disallow printing of this PDF.")
  @JsonProperty(JSON_PROPERTY_DISALLOW_PRINT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Boolean getDisallowPrint() {
    return disallowPrint;
  }


  @JsonProperty(JSON_PROPERTY_DISALLOW_PRINT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setDisallowPrint(Boolean disallowPrint) {
    this.disallowPrint = disallowPrint;
  }


  public PrinceOptions disallowCopy(Boolean disallowCopy) {

    this.disallowCopy = disallowCopy;
    return this;
  }

   /**
   * Disallow copying of this PDF.
   * @return disallowCopy
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "Disallow copying of this PDF.")
  @JsonProperty(JSON_PROPERTY_DISALLOW_COPY)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Boolean getDisallowCopy() {
    return disallowCopy;
  }


  @JsonProperty(JSON_PROPERTY_DISALLOW_COPY)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setDisallowCopy(Boolean disallowCopy) {
    this.disallowCopy = disallowCopy;
  }


  public PrinceOptions disallowAnnotate(Boolean disallowAnnotate) {

    this.disallowAnnotate = disallowAnnotate;
    return this;
  }

   /**
   * Disallow annotation of this PDF.
   * @return disallowAnnotate
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "Disallow annotation of this PDF.")
  @JsonProperty(JSON_PROPERTY_DISALLOW_ANNOTATE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Boolean getDisallowAnnotate() {
    return disallowAnnotate;
  }


  @JsonProperty(JSON_PROPERTY_DISALLOW_ANNOTATE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setDisallowAnnotate(Boolean disallowAnnotate) {
    this.disallowAnnotate = disallowAnnotate;
  }


  public PrinceOptions disallowModify(Boolean disallowModify) {

    this.disallowModify = disallowModify;
    return this;
  }

   /**
   * Disallow modification of this PDF.
   * @return disallowModify
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "Disallow modification of this PDF.")
  @JsonProperty(JSON_PROPERTY_DISALLOW_MODIFY)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Boolean getDisallowModify() {
    return disallowModify;
  }


  @JsonProperty(JSON_PROPERTY_DISALLOW_MODIFY)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setDisallowModify(Boolean disallowModify) {
    this.disallowModify = disallowModify;
  }


  public PrinceOptions debug(Boolean debug) {

    this.debug = debug;
    return this;
  }

   /**
   * Enable Prince debug mode.
   * @return debug
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "Enable Prince debug mode.")
  @JsonProperty(JSON_PROPERTY_DEBUG)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Boolean getDebug() {
    return debug;
  }


  @JsonProperty(JSON_PROPERTY_DEBUG)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setDebug(Boolean debug) {
    this.debug = debug;
  }


  public PrinceOptions input(InputEnum input) {

    this.input = input;
    return this;
  }

   /**
   * Specify the input format.
   * @return input
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "Specify the input format.")
  @JsonProperty(JSON_PROPERTY_INPUT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public InputEnum getInput() {
    return input;
  }


  @JsonProperty(JSON_PROPERTY_INPUT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setInput(InputEnum input) {
    this.input = input;
  }


  public PrinceOptions version(String version) {

    this.version = version;
    return this;
  }

   /**
   * Deprecated, use the appropriate &#x60;pipeline&#x60; version. Specify a specific verison of PrinceXML to use.
   * @return version
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "Deprecated, use the appropriate `pipeline` version. Specify a specific verison of PrinceXML to use.")
  @JsonProperty(JSON_PROPERTY_VERSION)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getVersion() {
    return version;
  }


  @JsonProperty(JSON_PROPERTY_VERSION)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setVersion(String version) {
    this.version = version;
  }


  public PrinceOptions javascript(Boolean javascript) {

    this.javascript = javascript;
    return this;
  }

   /**
   * Enable PrinceXML JavaScript. DocRaptor JavaScript parsing is also available elsewhere.
   * @return javascript
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "Enable PrinceXML JavaScript. DocRaptor JavaScript parsing is also available elsewhere.")
  @JsonProperty(JSON_PROPERTY_JAVASCRIPT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Boolean getJavascript() {
    return javascript;
  }


  @JsonProperty(JSON_PROPERTY_JAVASCRIPT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setJavascript(Boolean javascript) {
    this.javascript = javascript;
  }


  public PrinceOptions cssDpi(Integer cssDpi) {

    this.cssDpi = cssDpi;
    return this;
  }

   /**
   * Set the DPI when rendering CSS. Defaults to 96 but can be set with Prince 9.0 and up.
   * @return cssDpi
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "Set the DPI when rendering CSS. Defaults to 96 but can be set with Prince 9.0 and up.")
  @JsonProperty(JSON_PROPERTY_CSS_DPI)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Integer getCssDpi() {
    return cssDpi;
  }


  @JsonProperty(JSON_PROPERTY_CSS_DPI)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setCssDpi(Integer cssDpi) {
    this.cssDpi = cssDpi;
  }


  public PrinceOptions profile(String profile) {

    this.profile = profile;
    return this;
  }

   /**
   * In Prince 9.0 and up you can set the PDF profile.
   * @return profile
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "In Prince 9.0 and up you can set the PDF profile.")
  @JsonProperty(JSON_PROPERTY_PROFILE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getProfile() {
    return profile;
  }


  @JsonProperty(JSON_PROPERTY_PROFILE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setProfile(String profile) {
    this.profile = profile;
  }


  public PrinceOptions pdfTitle(String pdfTitle) {

    this.pdfTitle = pdfTitle;
    return this;
  }

   /**
   * Specify the PDF title, part of the document&#39;s metadata.
   * @return pdfTitle
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "Specify the PDF title, part of the document's metadata.")
  @JsonProperty(JSON_PROPERTY_PDF_TITLE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getPdfTitle() {
    return pdfTitle;
  }


  @JsonProperty(JSON_PROPERTY_PDF_TITLE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setPdfTitle(String pdfTitle) {
    this.pdfTitle = pdfTitle;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    PrinceOptions princeOptions = (PrinceOptions) o;
    return Objects.equals(this.baseurl, princeOptions.baseurl) &&
        Objects.equals(this.noXinclude, princeOptions.noXinclude) &&
        Objects.equals(this.noNetwork, princeOptions.noNetwork) &&
        Objects.equals(this.noParallelDownloads, princeOptions.noParallelDownloads) &&
        Objects.equals(this.httpUser, princeOptions.httpUser) &&
        Objects.equals(this.httpPassword, princeOptions.httpPassword) &&
        Objects.equals(this.httpProxy, princeOptions.httpProxy) &&
        Objects.equals(this.httpTimeout, princeOptions.httpTimeout) &&
        Objects.equals(this.insecure, princeOptions.insecure) &&
        Objects.equals(this.media, princeOptions.media) &&
        Objects.equals(this.noAuthorStyle, princeOptions.noAuthorStyle) &&
        Objects.equals(this.noDefaultStyle, princeOptions.noDefaultStyle) &&
        Objects.equals(this.noEmbedFonts, princeOptions.noEmbedFonts) &&
        Objects.equals(this.noSubsetFonts, princeOptions.noSubsetFonts) &&
        Objects.equals(this.noCompress, princeOptions.noCompress) &&
        Objects.equals(this.encrypt, princeOptions.encrypt) &&
        Objects.equals(this.keyBits, princeOptions.keyBits) &&
        Objects.equals(this.userPassword, princeOptions.userPassword) &&
        Objects.equals(this.ownerPassword, princeOptions.ownerPassword) &&
        Objects.equals(this.disallowPrint, princeOptions.disallowPrint) &&
        Objects.equals(this.disallowCopy, princeOptions.disallowCopy) &&
        Objects.equals(this.disallowAnnotate, princeOptions.disallowAnnotate) &&
        Objects.equals(this.disallowModify, princeOptions.disallowModify) &&
        Objects.equals(this.debug, princeOptions.debug) &&
        Objects.equals(this.input, princeOptions.input) &&
        Objects.equals(this.version, princeOptions.version) &&
        Objects.equals(this.javascript, princeOptions.javascript) &&
        Objects.equals(this.cssDpi, princeOptions.cssDpi) &&
        Objects.equals(this.profile, princeOptions.profile) &&
        Objects.equals(this.pdfTitle, princeOptions.pdfTitle);
  }

  @Override
  public int hashCode() {
    return Objects.hash(baseurl, noXinclude, noNetwork, noParallelDownloads, httpUser, httpPassword, httpProxy, httpTimeout, insecure, media, noAuthorStyle, noDefaultStyle, noEmbedFonts, noSubsetFonts, noCompress, encrypt, keyBits, userPassword, ownerPassword, disallowPrint, disallowCopy, disallowAnnotate, disallowModify, debug, input, version, javascript, cssDpi, profile, pdfTitle);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class PrinceOptions {\n");
    sb.append("    baseurl: ").append(toIndentedString(baseurl)).append("\n");
    sb.append("    noXinclude: ").append(toIndentedString(noXinclude)).append("\n");
    sb.append("    noNetwork: ").append(toIndentedString(noNetwork)).append("\n");
    sb.append("    noParallelDownloads: ").append(toIndentedString(noParallelDownloads)).append("\n");
    sb.append("    httpUser: ").append(toIndentedString(httpUser)).append("\n");
    sb.append("    httpPassword: ").append(toIndentedString(httpPassword)).append("\n");
    sb.append("    httpProxy: ").append(toIndentedString(httpProxy)).append("\n");
    sb.append("    httpTimeout: ").append(toIndentedString(httpTimeout)).append("\n");
    sb.append("    insecure: ").append(toIndentedString(insecure)).append("\n");
    sb.append("    media: ").append(toIndentedString(media)).append("\n");
    sb.append("    noAuthorStyle: ").append(toIndentedString(noAuthorStyle)).append("\n");
    sb.append("    noDefaultStyle: ").append(toIndentedString(noDefaultStyle)).append("\n");
    sb.append("    noEmbedFonts: ").append(toIndentedString(noEmbedFonts)).append("\n");
    sb.append("    noSubsetFonts: ").append(toIndentedString(noSubsetFonts)).append("\n");
    sb.append("    noCompress: ").append(toIndentedString(noCompress)).append("\n");
    sb.append("    encrypt: ").append(toIndentedString(encrypt)).append("\n");
    sb.append("    keyBits: ").append(toIndentedString(keyBits)).append("\n");
    sb.append("    userPassword: ").append(toIndentedString(userPassword)).append("\n");
    sb.append("    ownerPassword: ").append(toIndentedString(ownerPassword)).append("\n");
    sb.append("    disallowPrint: ").append(toIndentedString(disallowPrint)).append("\n");
    sb.append("    disallowCopy: ").append(toIndentedString(disallowCopy)).append("\n");
    sb.append("    disallowAnnotate: ").append(toIndentedString(disallowAnnotate)).append("\n");
    sb.append("    disallowModify: ").append(toIndentedString(disallowModify)).append("\n");
    sb.append("    debug: ").append(toIndentedString(debug)).append("\n");
    sb.append("    input: ").append(toIndentedString(input)).append("\n");
    sb.append("    version: ").append(toIndentedString(version)).append("\n");
    sb.append("    javascript: ").append(toIndentedString(javascript)).append("\n");
    sb.append("    cssDpi: ").append(toIndentedString(cssDpi)).append("\n");
    sb.append("    profile: ").append(toIndentedString(profile)).append("\n");
    sb.append("    pdfTitle: ").append(toIndentedString(pdfTitle)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

