#!/bin/bash
set -e
cd "$(dirname "$0")/.."

if [[ `ls target/*.jar` ]] && [ "$1" == "lazy" ]; then
  exit
fi

# check dependencies
which mvn > /dev/null     || (echo "mvn (aka maven) must be installed"; exit 1)
java -version > /dev/null || (echo "java must be installed"; exit 1)

mvn package
