#!/bin/bash
set -e
cd "`dirname \"$0\"`/.."

if [[ `ls target/*.jar` ]] && [ "$1" == "lazy" ]; then
  exit
fi

which mvn > /dev/null    || (echo "mvn (aka maven) must be installed"; exit 1)
mvn package
