#!/bin/sh
set -e
cd "`dirname \"$0\"`/.."

echo "Removing generated time annotations..."

# @javax.annotation.Generated(value = "class io.swagger.codegen.languages.JavaClientCodegen", date = "2016-01-14T21:48:19.329-05:00")

find src -name "*.java" -type f -exec sed -i '' 's/@javax\.annotation\.Generated.*$//g' {} +
