#!/bin/bash
set -e
cd "$(dirname "$0")/.."

./script/build

cd test

# runs a test file with PASS/FAIL message
run_test() {
  ../script/run_java_file $PWD/$1 && echo "PASS $1" || (echo "FAIL $1"; exit 1)
}

if [ "$1" == "" ]; then
  for test in $(ls *.java); do
    run_test $test
  done
else
  run_test $1.java
fi
