#!/bin/sh
set -e
cd "`dirname \"$0\"`/.."

mvn package

cd test

compile_and_run() {
  base_name=`basename -s .java $1`
  if [[ $string == *"_"* ]]; then
    cap_base_name=`echo $base_name | ruby -e "puts gets.split(/_/).map(&:capitalize).join"`
  else
    cap_base_name=$base_name
  fi
  javac -classpath .:"../target/swagger-java-client-1.0.0.jar" $cap_base_name.java
  java -classpath .:"../target/swagger-java-client-1.0.0.jar":"../target/lib/*" $cap_base_name
}

# runs a test file with PASS/FAIL message
run_test() {
  compile_and_run $1 && echo "PASS $1" || (echo "FAIL $1"; exit 1)
}

if [ "$1" == "" ]; then
  for test in $(ls *.java); do
    run_test $test
  done
else
  run_test $1.java
fi
